function y = Denoise_and_Bandpass_800_1000(x,tx)
%  Preprocess input x
%    This function expects an input vector x and a vector of time values
%    tx. tx is a numeric vector in units of seconds.

% Generated by MATLAB(R) 25.1 and Signal Processing Toolbox 25.1.
% Generated on: 04-Aug-2025 17:13:19

y = wdenoise(x, 8, ...
    'Wavelet', 'sym4', ...
    'DenoisingMethod', 'Bayes', ...
    'ThresholdRule', 'Median', ...
    'NoiseEstimate', 'LevelDependent');

Fs = 1/mean(diff(tx)); % Average sample rate
y = bandpass(y,[800 1000],Fs,'Steepness',0.85,'StopbandAttenuation',60);
